using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs; // this is fine

public sealed partial class RoundTab
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    public RoundTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartRoundCommand.OnPressed += _ => _console.ExecuteCommand("startround");
        EndRoundButton.OnPressed += _ => _console.ExecuteCommand("endround");
        RestartRoundButton.OnPressed += _ => _console.ExecuteCommand("restartround");
        RestartRoundNowButton.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
    }
}
