- type: entity
  id: CrateSecurityCombatGloves
  parent: CrateSecgear
  name: combat gloves crate
  description: A crate containing two pairs of combat gloves.
  components:
  - type: StorageFill
    contents:
    - id: ClothingHandsGlovesCombat
      amount: 2

- type: entity
  id: CrateSecurityPanicButtons
  parent: CrateSecgear
  name: distress signaller crate
  description: A crate containing four distress signallers.
  components:
  - type: StorageFill
    contents:
    - id: PanicButton
      amount: 4
