# SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BoxCardboard
  id: BoxTapeRecorder
  name: tape recorder box
  description: A box with colorful cassette tapes and a tape recorder.
  components:
  - type: Sprite
    layers:
    - state: box_security
    - sprite: _DV/Objects/Storage/boxes.rsi
      state: recorder
  - type: StorageFill
    contents:
    - id: CassetteTape
      amount: 4
    - id: TapeRecorder

# Prisoner Comms
- type: entity
  name: Prisoner encryption key box
  parent: BoxCardboard
  id: BoxEncryptionKeyPrisoner
  description: A box of spare encryption keys.
  components:
  - type: StorageFill
    contents:
      - id: EncryptionKeyPrison
        amount: 4
  - type: Sprite
    layers:
      - state: box
      - state: encryptokey
  - type: Storage
    whitelist:
      components:
      - EncryptionKey

- type: entity
  name: prisoner headset box
  parent: BoxCardboard
  id: BoxPrisonerHeadset
  description: A box of prisoner headsets.
  components:
  - type: StorageFill
    contents:
    - id: ClothingHeadsetPrison
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: headset
