// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Omu.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Omu.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class SignatureFontMenu : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystems = default!;

    public event Action<string?>? OnFontSelected;

    public SignatureFontMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(SignatureFontBoundUserInterfaceState state)
    {
        Fonts.DisposeAllChildren();

        AddOption(state.Name, state.OwnFont, Loc.GetString("signature-font-selector-own"), null, state.Font == null);

        var options = _entitySystems.GetEntitySystem<SignatureFontSystem>()
            .EnumerateFontTraits()
            .Select(option => (Name: Loc.GetString(option.Trait.Name), option.Trait.Description, option.Font))
            .OrderBy(option => option.Name);

        foreach (var (name, description, font) in options)
        {
            var caption = description is { } desc
                ? Loc.GetString("signature-font-selector-option", ("name", name), ("description", Loc.GetString(desc)))
                : name;

            AddOption(state.Name, font, caption, font, state.Font == font);
        }
    }

    private void AddOption(string signature, string previewFont, string caption, string? font, bool selected)
    {
        var preview = new FormattedMessage();
        preview.PushTag(new MarkupNode("font",
            new MarkupParameter(previewFont),
            new Dictionary<string, MarkupParameter> { ["size"] = new MarkupParameter(24) }));
        preview.AddText(signature);
        preview.Pop();

        var previewLabel = new RichTextLabel();
        previewLabel.SetMessage(preview, [typeof(FontTag)]);

        var button = new Button
        {
            ToggleMode = true,
            Pressed = selected,
            Margin = new Thickness(0, 2),
        };
        button.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(6, 4),
            Children =
            {
                previewLabel,
                new Label { Text = caption, StyleClasses = { StyleClass.LabelSubText } },
            },
        });
        button.OnPressed += _ => OnFontSelected?.Invoke(font);

        Fonts.AddChild(button);
    }
}
