# SPDX-License-Identifier: AGPL-3.0-or-later

- type: localizedDataset
  id: AlternateTitlesCargoTechnician
  values:
    prefix: job-name-alt-cargotech-
    count: 5

- type: localizedDataset
  id: AlternateTitlesQuartermaster
  values:
    prefix: job-name-alt-qm-
    count: 4

- type: localizedDataset
  id: AlternateTitlesSalvageSpecialist
  values:
    prefix: job-name-alt-salvagespec-
    count: 4

- type: localizedDataset
  id: AlternateTitlesCourier
  values:
    prefix: job-name-alt-courier-
    count: 3

- type: localizedDataset
  id: AlternateTitlesBartender
  values:
    prefix: job-name-alt-bartender-
    count: 4

- type: localizedDataset
  id: AlternateTitlesBotanist
  values:
    prefix: job-name-alt-botanist-
    count: 5

- type: localizedDataset
  id: AlternateTitlesChaplain
  values:
    prefix: job-name-alt-chaplain-
    count: 9

- type: localizedDataset
  id: AlternateTitlesChef
  values:
    prefix: job-name-alt-chef-
    count: 5

- type: localizedDataset
  id: AlternateTitlesClown
  values:
    prefix: job-name-alt-clown-
    count: 4

- type: localizedDataset
  id: AlternateTitlesJanitor
  values:
    prefix: job-name-alt-janitor-
    count: 4

- type: localizedDataset
  id: AlternateTitlesLawyer
  values:
    prefix: job-name-alt-lawyer-
    count: 7

- type: localizedDataset
  id: AlternateTitlesLibrarian
  values:
    prefix: job-name-alt-librarian-
    count: 5

- type: localizedDataset
  id: AlternateTitlesMime
  values:
    prefix: job-name-alt-mime-
    count: 1

- type: localizedDataset
  id: AlternateTitlesMusician
  values:
    prefix: job-name-alt-musician-
    count: 3

- type: localizedDataset
  id: AlternateTitlesServiceWorker
  values:
    prefix: job-name-alt-serviceworker-
    count: 5

- type: localizedDataset
  id: AlternateTitlesCaptain
  values:
    prefix: job-name-alt-captain-
    count: 6

- type: localizedDataset
  id: AlternateTitlesHeadOfPersonnel
  values:
    prefix: job-name-alt-hop-
    count: 3

- type: localizedDataset
  id: AlternateTitlesChiefEngineer
  values:
    prefix: job-name-alt-ce-
    count: 2

- type: localizedDataset
  id: AlternateTitlesChiefMedicalOfficer
  values:
    prefix: job-name-alt-cmo-
    count: 4

- type: localizedDataset
  id: AlternateTitlesHeadOfSecurity
  values:
    prefix: job-name-alt-hos-
    count: 3

- type: localizedDataset
  id: AlternateTitlesResearchDirector
  values:
    prefix: job-name-alt-rd-
    count: 5

- type: localizedDataset
  id: AlternateTitlesNanotrasenRepresentative
  values:
    prefix: job-name-alt-ntr-
    count: 3

- type: localizedDataset
  id: AlternateTitlesAdministrativeAssistant
  values:
    prefix: job-name-alt-admin-assistant-
    count: 3

- type: localizedDataset
  id: AlternateTitlesAtmosphericTechnician
  values:
    prefix: job-name-alt-atmostech-
    count: 3

- type: localizedDataset
  id: AlternateTitlesStationEngineer
  values:
    prefix: job-name-alt-engineer-
    count: 5

- type: localizedDataset
  id: AlternateTitlesMedicalDoctor
  values:
    prefix: job-name-alt-doctor-
    count: 6

- type: localizedDataset
  id: AlternateTitlesChemist
  values:
    prefix: job-name-alt-chemist-
    count: 3

- type: localizedDataset
  id: AlternateTitlesParamedic
  values:
    prefix: job-name-alt-paramedic-
    count: 3

- type: localizedDataset
  id: AlternateTitlesPsychologist
  values:
    prefix: job-name-alt-psychologist-
    count: 3

- type: localizedDataset
  id: AlternateTitlesVirologist
  values:
    prefix: job-name-alt-virologist-
    count: 3

- type: localizedDataset
  id: AlternateTitlesScientist
  values:
    prefix: job-name-alt-scientist-
    count: 5

- type: localizedDataset
  id: AlternateTitlesRoboticist
  values:
    prefix: job-name-alt-roboticist-
    count: 3

- type: localizedDataset
  id: AlternateTitlesWarden
  values:
    prefix: job-name-alt-warden-
    count: 2

- type: localizedDataset
  id: AlternateTitlesDetective
  values:
    prefix: job-name-alt-detective-
    count: 3

- type: localizedDataset
  id: AlternateTitlesSecuritySergeant
  values:
    prefix: job-name-alt-security-sergeant-
    count: 2

- type: localizedDataset
  id: AlternateTitlesBrigmedic
  values:
    prefix: job-name-alt-brigmedic-
    count: 3

- type: localizedDataset
  id: AlternateTitlesTransitPrisoner
  values:
    prefix: job-name-alt-transit-prisoner-
    count: 2

- type: localizedDataset
  id: AlternateTitlesReporter
  values:
    prefix: job-name-alt-reporter-
    count: 4

- type: localizedDataset
  id: AlternateTitlesRadioHost
  values:
    prefix: job-name-alt-radiohost-
    count: 3
